### ISSUE TITLE
Request - Weblate Integration

### ISSUE THREAD

**Issue by ghost** [hakandundar34coding/system-monitoring-center#19] opened 2022-01-18 09:04 UTC
Hi Hakan,

I think we are both Turkish but due to keep the issues clean, I have to write this request in English.

Do you know Weblate (https://weblate.org/en/). I think integrating your app to Weblate may help improve language support for your app.

I have translated MyPaint app (it's mostly written in Python) on Weblate.

**Comment by hakandundar34coding** [comment] 2022-01-19 07:19
Hi Sabri,

I did not know this site and I will review it.

I am closing this issue because it is not a bug. You can open a new one if there are another problems.

**Closed as completed** 2022-01-19 07:19 UTC
