### ISSUE TITLE
Services tab is empty - 2.9.0

### ISSUE THREAD

**Issue by greatbaracus** [hakandundar34coding/system-monitoring-center#152] opened 2023-03-23 22:51 UTC
```
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Services.py", line 499, in services_loop_func
    service_files_from_run_systemd_list = [filename.split("invocation:", 1)[1] for filename in os.listdir("/run/systemd/units/")]    # "/run/systemd/units/" directory contains loaded and non-dead services.
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Services.py", line 499, in <listcomp>
    service_files_from_run_systemd_list = [filename.split("invocation:", 1)[1] for filename in os.listdir("/run/systemd/units/")]    # "/run/systemd/units/" directory contains loaded and non-dead services.
IndexError: list index out of range

```

I have nothing in services tab, not only with version 2.9.0 but also with some previous versions. Honestly, i can't remember when it started to display no services.

**Comment by hakandundar34coding** [comment] 2023-03-24 08:17
Can you follow these steps?

- Open `Service.py` file in the installation folder (the file is in the `src` folder)
- Find line `499` and add `-` sign at the left of the `1`.
- Run the application from terminal by using: `system-monitoring-center` command
- Open `Services` tab and check service list
- Check terminal output and share it if there are errors.

Before:
```service_files_from_run_systemd_list = [filename.split("invocation:", 1)[1] ...```
After:
```service_files_from_run_systemd_list = [filename.split("invocation:", 1)[-1] ...```

**Comment by hakandundar34coding** [comment] 2023-04-05 13:25
It has been a long time since the last comment. I will close this issue.
But you can test the latest version of the application and write a comment if the problem is not fixed.

**Closed as completed** 2023-04-05 13:26 UTC
