### ISSUE TITLE
At processes tab, filtering for current user doesn't work if processes are shown as tree because parent tree node is different user

### ISSUE THREAD

**Issue by HelgeBoehme** [hakandundar34coding/system-monitoring-center#49] opened 2022-04-01 12:27 UTC
System Monitoring Center 1.8.0 on Ubuntu 20.04.4.

**Reproduce:**
If I enable Show processes as tree on Processes tab, and then select Show processes from this user, the process list is empty, because all processes owned by current user have parent tree node owned by different user, which is filtered.
![image](https://user-images.githubusercontent.com/16921350/161262627-9b3fef67-43b8-44f0-a4e2-a1aa27ee918a.png)

**Possible solution:**
If user or other users filtering is enabled, keep parent tree nodes visible but greyed-out.

**Comment by hakandundar34coding** [comment] 2022-04-04 09:07
The problem is fixed and source code is updated. A newer version of the application with the updated source code will be installable in about 1 week.

**Closed as completed by hakandundar34coding** 2022-04-04 09:07 UTC
