### ISSUE TITLE
Right click menu opens at the bottom of the application on systems with custom multiple monitors layout

### ISSUE THREAD

**Issue by gnarlin** [hakandundar34coding/system-monitoring-center#67] opened 2022-04-22 22:17 UTC
![right-click-menu](https://user-images.githubusercontent.com/8879429/164803005-c5571e56-de2c-4685-bb28-8f4039012864.png)

**Comment by gnarlin** [comment] 2022-04-22 22:19
Running on Ubuntu 20.04 with two monitors. 1: 34" 3440x1440 2:22" 1920x1080.

**Comment by hakandundar34coding** [comment] 2022-04-23 05:05
Are there any menu problems on other tabs? Is it only on Services tab?

Can you share screenshot of the System tab? I want to learn more details such as window manager, etc.

**Comment by gnarlin** [comment] 2022-04-23 12:25
Every tab has this problem.

**Comment by hakandundar34coding** [comment] 2022-04-23 12:36
What is your desktop environment, windowing system and window manager?

**Comment by gnarlin** [comment] 2022-04-23 12:39
Ubuntu 21.10 Gnome desktop (I said the wrong version previously).

**Comment by hakandundar34coding** [comment] 2022-04-23 12:41
Does this happen on every right click?

**Comment by gnarlin** [comment] 2022-04-23 12:42
Yes.

**Comment by hakandundar34coding** [comment] 2022-04-23 12:43
What happens if you left click (select the row) and after that right click on the same row?

**Comment by gnarlin** [comment] 2022-04-23 12:45
Doesn't matter if I do it that way or not. The right click menu always pops up near the bottom of the window.
If I click on something that's near the bottom of the window the right click menu pops up at the right place.

**Comment by gnarlin** [comment] 2022-04-23 12:46
Where does the application store it's preferences? Is it somewhere in .config? I want to try to wipe out the config and start it up again like it was freshly installed.

**Comment by hakandundar34coding** [comment] 2022-04-23 12:48
I do not know if it is easy to disconnect one of your monitors.

Can you try these steps?

- Close the application.
- Disconnect one monitor.
- Run the application.
- Right click on a row.

**Comment by gnarlin** [comment] 2022-04-23 12:48
I'm using Wayland btw. I'll test on x11.

**Comment by gnarlin** [comment] 2022-04-23 12:53
Yup. As soon as I reverted to a single monitor the right click menus worked normally so this has something to do with having multiple monitors. I manually position the secondary monitor below the primary monitor in the Gnome display settings.

**Comment by hakandundar34coding** [comment] 2022-04-23 12:56
Is there a setting for multiple monitors to use the application without right click menu problem?

**Comment by gnarlin** [comment] 2022-04-23 12:57
When arranged so that the bottom of the monitors are aligned the right click menu pop up at the expected locations.
![screens1](https://user-images.githubusercontent.com/8879429/164895461-ff14b7d6-8adf-4294-9e23-82a066deb089.png)
When arranged so that the secondary monitors bottom is lower than the primary monitors the right click menus always pop up near the bottom.
![screens2](https://user-images.githubusercontent.com/8879429/164895465-bfc97425-cadb-4f59-a14b-060ca4c7a05e.png)

**Comment by hakandundar34coding** [comment] 2022-04-23 13:01
GTK toolkit manages this menu position.
What is the physical positioning of your monitors? Is the problem solved?

**Comment by gnarlin** [comment] 2022-04-23 13:18
Well, no because I arrange the monitor positions so that the mouse doesn't jump down when I move it between the monitors.
Also, it's can't be the GTK toolkit. Right click menus position work normally in the Gnome system-monitor regardless of the monitors logical arrangements. Maybe it's the python GTK implementation?

**Comment by hakandundar34coding** [comment] 2022-04-23 13:30
I do not know. This is the code to get mouse position:
```
def on_treeview2101_button_press_event(widget, event):
    path, _, _, _ = treeview2101.get_path_at_pos(int(event.x), int(event.y))
```

Button press event documentation [link](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/Widget.html#Gtk.Widget.signals.button_press_event).

I will try to learn more details about the problem.

**Comment by hakandundar34coding** [comment] 2022-04-23 13:34
Can you try on newer version of Ubuntu?

**Comment by hakandundar34coding** [comment] 2022-04-23 13:47
There are several right click menu bug reports on the web. Some of them does not happen on all applications.

There may be a problem with the window manager. Mutter is used on Gnome DE. It is integrated. I do not know if another window manager can be installed on Gnome.

Can you try on a newer version of Ubuntu or another distribution?

or

Can you try on a different desktop environment?

You can test the application on "try" modes of ISO files without installing the OS.

----------------------------

About the config [file](https://github.com/hakandundar34coding/system-monitoring-center/issues/67#issuecomment-1107466155):
Config file path:
`/home/[user_name]/.config/system-monitoring-center/config.txt`

**Comment by hakandundar34coding** [comment] 2022-04-27 07:04
Have you tried right clicking on [other](https://github.com/hakandundar34coding/system-monitoring-center/issues/67#issuecomment-1107474907) systems?

**Comment by theofficialgman** [comment] 2022-05-02 04:36
I have been using this on Ubuntu 22.04 gnome (with mutter) and KDE plasma (with kwin) both on wayland and can reproduce this issue when the second monitor is slightly below the first (as seen here) https://github.com/hakandundar34coding/system-monitoring-center/issues/67#issuecomment-1107467577

I have not observed this exact issue in other applications. However, I am aware of a similar bug in QT5 (which this does not use) when the second monitor is not aligned with the top edge of the first monitor. Funny how multiple graphical toolkits manage to get this wrong.

**Comment by hakandundar34coding** [comment] 2022-05-05 13:04
@gnarlin, @theofficialgman 
The application is updated (v1.14.0) and there are minor changes for right click menus. Can you write if the problem is solved?

**Comment by theofficialgman** [comment] 2022-05-05 21:36
> @gnarlin, @theofficialgman The application is updated (v1.14.0) and there are minor changes for right click menus. Can you write if the problem is solved?

seems to be working perfectly on kwin wayland (haven't tested in gnome wayland)

**Comment by hakandundar34coding** [comment] 2022-05-09 08:53
@gnarlin
It has been a long time since your last comment. There were improvements for fixing this bug. The problem is fixed for kwin window manager on Wayland windowing system with multiple monitors. I will close this issue. But you can write comments if there are problems on your system.

**Closed as completed by hakandundar34coding** 2022-05-09 08:53 UTC
